-- 14 new card themes (20 total). ADD VALUE IF NOT EXISTS keeps this
-- idempotent; Postgres 12+ allows it inside the migration transaction.
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'OCEAN';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'FOREST';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'SUNSET';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'ROSE';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'INDIGO';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'TEAL';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'AMBER';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'CRIMSON';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'LAVENDER';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MIDNIGHT';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'SKY';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MINT';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'PEACH';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'GRAPHITE';
